package Futbol;

public enum Provincia {
    BUENOS_AIRES,CATAMARCA, CHACO, CHUBUT, CORRIENTES, CORDOBA, ENTRE_RIOS, FORMOSA, JUJUY, LA_PAMPA, LA_RIOJA, MENDOZA, MISIONES, NEUQUEN, RIO_NEGRO, SAN_JUAN, SALTA, SAN_LUIS, SANTA_CRUZ, SANTA_FE, SANTIAGO_DEL_ESTERO, TIERRA_DEL_FUEGO, TUCUMAN, CABA
    }
